version: 0.8.5.{build}
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: >-
    git submodule update --init --recursive

    build_all.bat
artifacts:
  - path: src/bin/MonoGame/Release/SpriteFontPlus.$(appveyor_build_version).nupkg
    name: SpriteFontPlus.nupkg

  - path: SpriteFontPlus.$(appveyor_build_version).zip
    name: ZipPackage
deploy:
  - provider: GitHub
    release: $(appveyor_build_version)
    description: $(appveyor_build_version)
    auth_token:
      secure: nIpZ5N6iQIXVV8/kK/Y6BqY4KYD+y7HYdq+vTKv+LqZBbxHE9BuEgZAHGVDvmJKh
    artifact: ZipPackage
    draft: false
    prerelease: false
    
  - provider: NuGet	
    api_key:
      secure: oy2ef45v2k4cuzejz2yaw5fpfds6xfnufcorjbltmjxxi4
    artifact: /.*\.nupkg/